# Generated by Django 5.2.15 on 2026-07-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banner_show_everywhere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-created_at', 'display_order')},
        ),
    ]
