COUNTRIES = [
    ("AF", "Afghanistan"), ("AL", "Albania"), ("DZ", "Algeria"), ("AD", "Andorra"),
    ("AO", "Angola"), ("AG", "Antigua and Barbuda"), ("AR", "Argentina"), ("AM", "Armenia"),
    ("AU", "Australia"), ("AT", "Austria"), ("AZ", "Azerbaijan"), ("BS", "Bahamas"),
    ("BH", "Bahrain"), ("BD", "Bangladesh"), ("BB", "Barbados"), ("BY", "Belarus"),
    ("BE", "Belgium"), ("BZ", "Belize"), ("BJ", "Benin"), ("BT", "Bhutan"),
    ("BO", "Bolivia"), ("BA", "Bosnia and Herzegovina"), ("BW", "Botswana"), ("BR", "Brazil"),
    ("BN", "Brunei"), ("BG", "Bulgaria"), ("BF", "Burkina Faso"), ("BI", "Burundi"),
    ("CV", "Cabo Verde"), ("KH", "Cambodia"), ("CM", "Cameroon"), ("CA", "Canada"),
    ("CF", "Central African Republic"), ("TD", "Chad"), ("CL", "Chile"), ("CN", "China"),
    ("CO", "Colombia"), ("KM", "Comoros"), ("CG", "Congo"), ("CD", "Congo, Democratic Republic"),
    ("CR", "Costa Rica"), ("CI", "Cote d'Ivoire"), ("HR", "Croatia"), ("CU", "Cuba"),
    ("CY", "Cyprus"), ("CZ", "Czechia"), ("DK", "Denmark"), ("DJ", "Djibouti"),
    ("DM", "Dominica"), ("DO", "Dominican Republic"), ("EC", "Ecuador"), ("EG", "Egypt"),
    ("SV", "El Salvador"), ("GQ", "Equatorial Guinea"), ("ER", "Eritrea"), ("EE", "Estonia"),
    ("SZ", "Eswatini"), ("ET", "Ethiopia"), ("FJ", "Fiji"), ("FI", "Finland"),
    ("FR", "France"), ("GA", "Gabon"), ("GM", "Gambia"), ("GE", "Georgia"),
    ("DE", "Germany"), ("GH", "Ghana"), ("GR", "Greece"), ("GD", "Grenada"),
    ("GT", "Guatemala"), ("GN", "Guinea"), ("GW", "Guinea-Bissau"), ("GY", "Guyana"),
    ("HT", "Haiti"), ("HN", "Honduras"), ("HU", "Hungary"), ("IS", "Iceland"),
    ("IN", "India"), ("ID", "Indonesia"), ("IR", "Iran"), ("IQ", "Iraq"),
    ("IE", "Ireland"), ("IL", "Israel"), ("IT", "Italy"), ("JM", "Jamaica"),
    ("JP", "Japan"), ("JO", "Jordan"), ("KZ", "Kazakhstan"), ("KE", "Kenya"),
    ("KI", "Kiribati"), ("KP", "North Korea"), ("KR", "South Korea"), ("KW", "Kuwait"),
    ("KG", "Kyrgyzstan"), ("LA", "Laos"), ("LV", "Latvia"), ("LB", "Lebanon"),
    ("LS", "Lesotho"), ("LR", "Liberia"), ("LY", "Libya"), ("LI", "Liechtenstein"),
    ("LT", "Lithuania"), ("LU", "Luxembourg"), ("MG", "Madagascar"), ("MW", "Malawi"),
    ("MY", "Malaysia"), ("MV", "Maldives"), ("ML", "Mali"), ("MT", "Malta"),
    ("MH", "Marshall Islands"), ("MR", "Mauritania"), ("MU", "Mauritius"), ("MX", "Mexico"),
    ("FM", "Micronesia"), ("MD", "Moldova"), ("MC", "Monaco"), ("MN", "Mongolia"),
    ("ME", "Montenegro"), ("MA", "Morocco"), ("MZ", "Mozambique"), ("MM", "Myanmar"),
    ("NA", "Namibia"), ("NR", "Nauru"), ("NP", "Nepal"), ("NL", "Netherlands"),
    ("NZ", "New Zealand"), ("NI", "Nicaragua"), ("NE", "Niger"), ("NG", "Nigeria"),
    ("MK", "North Macedonia"), ("NO", "Norway"), ("OM", "Oman"), ("PK", "Pakistan"),
    ("PW", "Palau"), ("PS", "Palestine"), ("PA", "Panama"), ("PG", "Papua New Guinea"),
    ("PY", "Paraguay"), ("PE", "Peru"), ("PH", "Philippines"), ("PL", "Poland"),
    ("PT", "Portugal"), ("QA", "Qatar"), ("RO", "Romania"), ("RU", "Russia"),
    ("RW", "Rwanda"), ("KN", "Saint Kitts and Nevis"), ("LC", "Saint Lucia"),
    ("VC", "Saint Vincent and the Grenadines"), ("WS", "Samoa"), ("SM", "San Marino"),
    ("ST", "Sao Tome and Principe"), ("SA", "Saudi Arabia"), ("SN", "Senegal"),
    ("RS", "Serbia"), ("SC", "Seychelles"), ("SL", "Sierra Leone"), ("SG", "Singapore"),
    ("SK", "Slovakia"), ("SI", "Slovenia"), ("SB", "Solomon Islands"), ("SO", "Somalia"),
    ("ZA", "South Africa"), ("SS", "South Sudan"), ("ES", "Spain"), ("LK", "Sri Lanka"),
    ("SD", "Sudan"), ("SR", "Suriname"), ("SE", "Sweden"), ("CH", "Switzerland"),
    ("SY", "Syria"), ("TW", "Taiwan"), ("TJ", "Tajikistan"), ("TZ", "Tanzania"),
    ("TH", "Thailand"), ("TL", "Timor-Leste"), ("TG", "Togo"), ("TO", "Tonga"),
    ("TT", "Trinidad and Tobago"), ("TN", "Tunisia"), ("TR", "Turkiye"), ("TM", "Turkmenistan"),
    ("TV", "Tuvalu"), ("UG", "Uganda"), ("UA", "Ukraine"), ("AE", "United Arab Emirates"),
    ("GB", "United Kingdom"), ("US", "United States"), ("UY", "Uruguay"), ("UZ", "Uzbekistan"),
    ("VU", "Vanuatu"), ("VA", "Vatican City"), ("VE", "Venezuela"), ("VN", "Vietnam"),
    ("YE", "Yemen"), ("ZM", "Zambia"), ("ZW", "Zimbabwe"),
]

INDIA_STATES = [
    "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat",
    "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh",
    "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab",
    "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh",
    "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands", "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Jammu and Kashmir", "Ladakh",
    "Lakshadweep", "Puducherry",
]

INDIA_STATE_HINDI_NAMES = {
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Arunachal Pradesh": "अरुणाचल प्रदेश",
    "Assam": "असम",
    "Bihar": "बिहार",
    "Chhattisgarh": "छत्तीसगढ़",
    "Goa": "गोवा",
    "Gujarat": "गुजरात",
    "Haryana": "हरियाणा",
    "Himachal Pradesh": "हिमाचल प्रदेश",
    "Jharkhand": "झारखंड",
    "Karnataka": "कर्नाटक",
    "Kerala": "केरल",
    "Madhya Pradesh": "मध्य प्रदेश",
    "Maharashtra": "महाराष्ट्र",
    "Manipur": "मणिपुर",
    "Meghalaya": "मेघालय",
    "Mizoram": "मिजोरम",
    "Nagaland": "नागालैंड",
    "Odisha": "ओडिशा",
    "Punjab": "पंजाब",
    "Rajasthan": "राजस्थान",
    "Sikkim": "सिक्किम",
    "Tamil Nadu": "तमिलनाडु",
    "Telangana": "तेलंगाना",
    "Tripura": "त्रिपुरा",
    "Uttar Pradesh": "उत्तर प्रदेश",
    "Uttarakhand": "उत्तराखंड",
    "West Bengal": "पश्चिम बंगाल",
    "Andaman and Nicobar Islands": "अंडमान और निकोबार द्वीपसमूह",
    "Chandigarh": "चंडीगढ़",
    "Dadra and Nagar Haveli and Daman and Diu": "दादरा और नगर हवेली और दमन और दीव",
    "Delhi": "दिल्ली",
    "Jammu and Kashmir": "जम्मू और कश्मीर",
    "Ladakh": "लद्दाख",
    "Lakshadweep": "लक्षद्वीप",
    "Puducherry": "पुदुचेरी",
}


COUNTRY_HINDI_NAMES = {
    "Afghanistan": "अफगानिस्तान",
    "Albania": "अल्बानिया",
    "Algeria": "अल्जीरिया",
    "Andorra": "अंडोरा",
    "Angola": "अंगोला",
    "Antigua and Barbuda": "एंटीगुआ और बारबुडा",
    "Argentina": "अर्जेंटीना",
    "Armenia": "आर्मेनिया",
    "Australia": "ऑस्ट्रेलिया",
    "Austria": "ऑस्ट्रिया",
    "Azerbaijan": "अजरबैजान",
    "Bahamas": "बहामास",
    "Bahrain": "बहरीन",
    "Bangladesh": "बांग्लादेश",
    "Barbados": "बारबाडोस",
    "Belarus": "बेलारूस",
    "Belgium": "बेल्जियम",
    "Belize": "बेलीज",
    "Benin": "बेनिन",
    "Bhutan": "भूटान",
    "Bolivia": "बोलीविया",
    "Bosnia and Herzegovina": "बोस्निया और हर्जेगोविना",
    "Botswana": "बोत्सवाना",
    "Brazil": "ब्राजील",
    "Brunei": "ब्रुनेई",
    "Bulgaria": "बुल्गारिया",
    "Burkina Faso": "बुर्किना फासो",
    "Burundi": "बुरुंडी",
    "Cabo Verde": "केप वर्डे",
    "Cambodia": "कंबोडिया",
    "Cameroon": "कैमरून",
    "Canada": "कनाडा",
    "Central African Republic": "मध्य अफ्रीकी गणराज्य",
    "Chad": "चाड",
    "Chile": "चिली",
    "China": "चीन",
    "Colombia": "कोलंबिया",
    "Comoros": "कोमोरोस",
    "Congo": "कांगो",
    "Congo, Democratic Republic": "कांगो लोकतांत्रिक गणराज्य",
    "Costa Rica": "कोस्टा रिका",
    "Cote d'Ivoire": "कोट डी आइवर",
    "Croatia": "क्रोएशिया",
    "Cuba": "क्यूबा",
    "Cyprus": "साइप्रस",
    "Czechia": "चेकिया",
    "Denmark": "डेनमार्क",
    "Djibouti": "जिबूती",
    "Dominica": "डोमिनिका",
    "Dominican Republic": "डोमिनिकन गणराज्य",
    "Ecuador": "इक्वाडोर",
    "Egypt": "मिस्र",
    "El Salvador": "अल साल्वाडोर",
    "Equatorial Guinea": "इक्वेटोरियल गिनी",
    "Eritrea": "इरिट्रिया",
    "Estonia": "एस्टोनिया",
    "Eswatini": "एस्वातिनी",
    "Ethiopia": "इथियोपिया",
    "Fiji": "फिजी",
    "Finland": "फिनलैंड",
    "France": "फ्रांस",
    "Gabon": "गैबॉन",
    "Gambia": "गाम्बिया",
    "Georgia": "जॉर्जिया",
    "Germany": "जर्मनी",
    "Ghana": "घाना",
    "Greece": "ग्रीस",
    "Grenada": "ग्रेनेडा",
    "Guatemala": "ग्वाटेमाला",
    "Guinea": "गिनी",
    "Guinea-Bissau": "गिनी-बिसाऊ",
    "Guyana": "गुयाना",
    "Haiti": "हैती",
    "Honduras": "होंडुरास",
    "Hungary": "हंगरी",
    "Iceland": "आइसलैंड",
    "India": "भारत",
    "Indonesia": "इंडोनेशिया",
    "Iran": "ईरान",
    "Iraq": "इराक",
    "Ireland": "आयरलैंड",
    "Israel": "इजराइल",
    "Italy": "इटली",
    "Jamaica": "जमैका",
    "Japan": "जापान",
    "Jordan": "जॉर्डन",
    "Kazakhstan": "कजाखस्तान",
    "Kenya": "केन्या",
    "Kiribati": "किरिबाती",
    "North Korea": "उत्तर कोरिया",
    "South Korea": "दक्षिण कोरिया",
    "Kuwait": "कुवैत",
    "Kyrgyzstan": "किर्गिस्तान",
    "Laos": "लाओस",
    "Latvia": "लातविया",
    "Lebanon": "लेबनान",
    "Lesotho": "लेसोथो",
    "Liberia": "लाइबेरिया",
    "Libya": "लीबिया",
    "Liechtenstein": "लिकटेंस्टीन",
    "Lithuania": "लिथुआनिया",
    "Luxembourg": "लक्जमबर्ग",
    "Madagascar": "मेडागास्कर",
    "Malawi": "मलावी",
    "Malaysia": "मलेशिया",
    "Maldives": "मालदीव",
    "Mali": "माली",
    "Malta": "माल्टा",
    "Marshall Islands": "मार्शल द्वीपसमूह",
    "Mauritania": "मॉरिटानिया",
    "Mauritius": "मॉरीशस",
    "Mexico": "मेक्सिको",
    "Micronesia": "माइक्रोनेशिया",
    "Moldova": "मोल्दोवा",
    "Monaco": "मोनाको",
    "Mongolia": "मंगोलिया",
    "Montenegro": "मोंटेनेग्रो",
    "Morocco": "मोरक्को",
    "Mozambique": "मोजाम्बिक",
    "Myanmar": "म्यांमार",
    "Namibia": "नामीबिया",
    "Nauru": "नाउरू",
    "Nepal": "नेपाल",
    "Netherlands": "नीदरलैंड",
    "New Zealand": "न्यूजीलैंड",
    "Nicaragua": "निकारागुआ",
    "Niger": "नाइजर",
    "Nigeria": "नाइजीरिया",
    "North Macedonia": "उत्तर मैसेडोनिया",
    "Norway": "नॉर्वे",
    "Oman": "ओमान",
    "Pakistan": "पाकिस्तान",
    "Palau": "पलाऊ",
    "Palestine": "फिलिस्तीन",
    "Panama": "पनामा",
    "Papua New Guinea": "पापुआ न्यू गिनी",
    "Paraguay": "पराग्वे",
    "Peru": "पेरू",
    "Philippines": "फिलीपींस",
    "Poland": "पोलैंड",
    "Portugal": "पुर्तगाल",
    "Qatar": "कतर",
    "Romania": "रोमानिया",
    "Russia": "रूस",
    "Rwanda": "रवांडा",
    "Saint Kitts and Nevis": "सेंट किट्स और नेविस",
    "Saint Lucia": "सेंट लूसिया",
    "Saint Vincent and the Grenadines": "सेंट विंसेंट और ग्रेनेडाइंस",
    "Samoa": "समोआ",
    "San Marino": "सैन मैरीनो",
    "Sao Tome and Principe": "साओ टोमे और प्रिंसिपे",
    "Saudi Arabia": "सऊदी अरब",
    "Senegal": "सेनेगल",
    "Serbia": "सर्बिया",
    "Seychelles": "सेशेल्स",
    "Sierra Leone": "सिएरा लियोन",
    "Singapore": "सिंगापुर",
    "Slovakia": "स्लोवाकिया",
    "Slovenia": "स्लोवेनिया",
    "Solomon Islands": "सोलोमन द्वीपसमूह",
    "Somalia": "सोमालिया",
    "South Africa": "दक्षिण अफ्रीका",
    "South Sudan": "दक्षिण सूडान",
    "Spain": "स्पेन",
    "Sri Lanka": "श्रीलंका",
    "Sudan": "सूडान",
    "Suriname": "सूरीनाम",
    "Sweden": "स्वीडन",
    "Switzerland": "स्विट्जरलैंड",
    "Syria": "सीरिया",
    "Taiwan": "ताइवान",
    "Tajikistan": "ताजिकिस्तान",
    "Tanzania": "तंजानिया",
    "Thailand": "थाईलैंड",
    "Timor-Leste": "तिमोर-लेस्ते",
    "Togo": "टोगो",
    "Tonga": "टोंगा",
    "Trinidad and Tobago": "त्रिनिदाद और टोबैगो",
    "Tunisia": "ट्यूनीशिया",
    "Turkiye": "तुर्किये",
    "Turkmenistan": "तुर्कमेनिस्तान",
    "Tuvalu": "तुवालू",
    "Uganda": "युगांडा",
    "Ukraine": "यूक्रेन",
    "United Arab Emirates": "संयुक्त अरब अमीरात",
    "United Kingdom": "यूनाइटेड किंगडम",
    "United States": "संयुक्त राज्य अमेरिका",
    "Uruguay": "उरुग्वे",
    "Uzbekistan": "उज्बेकिस्तान",
    "Vanuatu": "वानुअतु",
    "Vatican City": "वेटिकन सिटी",
    "Venezuela": "वेनेजुएला",
    "Vietnam": "वियतनाम",
    "Yemen": "यमन",
    "Zambia": "जाम्बिया",
    "Zimbabwe": "जिम्बाब्वे",
}


def hindi_country_name(country_name):
    return COUNTRY_HINDI_NAMES.get(country_name, country_name)


def hindi_state_name(state_name):
    return INDIA_STATE_HINDI_NAMES.get(state_name, state_name)
