SUPPORTED_LANGUAGES = {
    "hi": "हिन्दी",
    "en": "English",
}

LANGUAGE_SESSION_KEY = "site_language"
LANGUAGE_COOKIE_NAME = "site_language"

UI_TEXT = {
    "site_name": {"hi": "धर्म रक्षा संघ", "en": "Dharm Raksha Sangh"},
    "nav_toggle": {"hi": "मेनू खोलें", "en": "Open menu"},
    "home": {"hi": "होम", "en": "Home"},
    "about": {"hi": "परिचय", "en": "About"},
    "contact": {"hi": "संपर्क", "en": "Contact"},
    "events": {"hi": "कार्यक्रम", "en": "Events"},
    "seva_prakalp": {"hi": "प्रकल्प", "en": "Prakalp"},
    "hamare_stambh": {"hi": "स्तंभ", "en": "Stambh"},
    "patrika": {"hi": "पत्रिका", "en": "Patrika"},
    "membership": {"hi": "सदस्यता", "en": "Membership"},
    "donate": {"hi": "दान करें", "en": "Donate"},
    "login": {"hi": "लॉगिन", "en": "Login"},
    "logout": {"hi": "लॉगआउट", "en": "Logout"},
    "join": {"hi": "जुड़ें", "en": "Join"},
    "language": {"hi": "भाषा", "en": "Language"},
    "footer_about": {
        "hi": "संगठित सेवा प्रकल्प, सांस्कृतिक मूल्यों और समाज सेवा के माध्यम से राष्ट्रधर्म की सेवा.",
        "en": "Serving society through organized seva prakalp, cultural values, and community action.",
    },
    "hero_eyebrow": {"hi": "सेवा. संस्कार. समर्पण.", "en": "Seva. Sanskar. Samarpan."},
    "welcome": {
        "hi": "धर्म रक्षा संघ की आधिकारिक वेबसाइट पर आपका स्वागत है.",
        "en": "Welcome to the official website of Dharm Raksha Sangh.",
    },
    "view": {"hi": "देखें", "en": "View"},
    "all_seva": {"hi": "सभी सेवा प्रकल्प", "en": "All Seva Prakalp"},
    "active_prakalp": {"hi": "सक्रिय सेवा प्रकल्प", "en": "Active Seva Prakalp"},
    "core_values": {"hi": "मूल मूल्य", "en": "Core values"},
    "seva": {"hi": "सेवा", "en": "Seva"},
    "sanskar": {"hi": "संस्कार", "en": "Sanskar"},
    "sangathan": {"hi": "संगठन", "en": "Sangathan"},
    "seva_desc": {"hi": "समर्पण के साथ समाज सेवा", "en": "Service to society with dedication"},
    "sanskar_desc": {"hi": "हर पीढ़ी के लिए सांस्कृतिक मूल्य", "en": "Cultural values for every generation"},
    "sangathan_desc": {"hi": "स्थायी प्रभाव के लिए संगठित प्रयास", "en": "Organized effort for lasting impact"},
    "stambh_heading": {"hi": "मिशन को दिशा देने वाले व्यक्तित्व", "en": "People guiding the mission"},
    "view_all": {"hi": "सभी देखें", "en": "View all"},
    "read_details": {"hi": "विवरण पढ़ें", "en": "Read details"},
    "publications": {"hi": "प्रकाशन", "en": "Publications"},
    "featured_issue": {"hi": "विशेष अंक", "en": "Featured issue"},
    "pdf_download": {"hi": "PDF डाउनलोड", "en": "Download PDF"},
    "read_epaper": {"hi": "पत्रिका पढ़ें", "en": "Read Patrika"},
    "cta_title": {"hi": "धर्म रक्षा संघ", "en": "Dharm Raksha Sangh"},
    "cta_text": {
        "hi": "हर प्रकल्प सेवा भाव रखने वाले लोगों से शुरू होता है.",
        "en": "Every prakalp begins with people who carry the spirit of service.",
    },
    "explore_seva": {"hi": "सेवा प्रकल्प देखें", "en": "Explore Seva Prakalp"},
    "contact_us": {"hi": "संपर्क करें", "en": "Contact Us"},
    "email": {"hi": "ईमेल", "en": "Email"},
    "mobile": {"hi": "मोबाइल", "en": "Mobile"},
    "bank_details": {"hi": "बैंक विवरण", "en": "Bank Details"},
    "account_info": {"hi": "खाता जानकारी", "en": "Account Information"},
    "scan_donate": {"hi": "स्कैन करें और दान दें", "en": "Scan and Donate"},
    "our_work": {"hi": "हमारा कार्य", "en": "Our Work"},
    "seva_index_desc": {
        "hi": "धर्म रक्षा संघ के सक्रिय सेवा कार्यों और प्रकल्पों को देखें.",
        "en": "Explore the active service work and prakalp of Dharm Raksha Sangh.",
    },
    "no_prakalp": {"hi": "अभी कोई सेवा प्रकल्प उपलब्ध नहीं है.", "en": "No seva prakalp are available yet."},
    "our_pillars": {"hi": "हमारे स्तंभ", "en": "Our Pillars"},
    "stambh_desc": {
        "hi": "धर्म रक्षा संघ की प्रेरणा, मार्गदर्शन और संगठन शक्ति.",
        "en": "The inspiration, guidance, and organizing strength of Dharm Raksha Sangh.",
    },
    "featured": {"hi": "विशेष", "en": "Featured"},
    "no_stambh": {"hi": "अभी कोई स्तंभ उपलब्ध नहीं है.", "en": "No pillars are available yet."},
    "events_desc": {
        "hi": "धर्म रक्षा संघ के स्थायी, वर्तमान, विशेष और पूर्व कार्यक्रम.",
        "en": "Permanent, current, featured, and past events of Dharm Raksha Sangh.",
    },
    "featured_events": {"hi": "विशेष कार्यक्रम", "en": "Featured Events"},
    "any_time": {"hi": "स्थायी", "en": "Any Time"},
    "any_time_events": {"hi": "स्थायी कार्यक्रम", "en": "Any Time Events"},
    "current_events": {"hi": "वर्तमान कार्यक्रम", "en": "Current Events"},
    "past_events": {"hi": "पूर्व कार्यक्रम", "en": "Past Events"},
    "no_events": {"hi": "अभी कोई कार्यक्रम उपलब्ध नहीं है.", "en": "No events are available yet."},
    "back_events": {"hi": "कार्यक्रमों पर वापस", "en": "Back to events"},
    "back_seva": {"hi": "सेवा प्रकल्प पर वापस", "en": "Back to seva prakalp"},
    "back_stambh": {"hi": "हमारे स्तंभ पर वापस", "en": "Back to hamare stambh"},
    "patrika_desc": {
        "hi": "धर्म रक्षा संघ की अपलोड की गई पत्रिकाएं पढ़ें और डाउनलोड करें.",
        "en": "Read and download Dharm Raksha Sangh patrika issues uploaded from the admin panel.",
    },
    "no_patrika": {"hi": "अभी कोई पत्रिका उपलब्ध नहीं है.", "en": "No patrika issues are available yet."},
    "my_profile": {"hi": "मेरी प्रोफाइल", "en": "My Profile"},
    "member_profile": {"hi": "सदस्य प्रोफाइल", "en": "Member Profile"},
    "update_details": {"hi": "विवरण अपडेट करें", "en": "Update Details"},
    "save_details": {"hi": "विवरण सेव करें", "en": "Save Details"},
    "subscriptions": {"hi": "सदस्यता", "en": "Subscriptions"},
    "valid_until": {"hi": "तक मान्य", "en": "Valid until"},
    "no_membership": {"hi": "अभी कोई सक्रिय सदस्यता नहीं है.", "en": "No active membership yet."},
    "choose_membership": {"hi": "सदस्यता लें", "en": "Choose Membership"},
    "certificates": {"hi": "प्रमाणपत्र", "en": "Certificates"},
    "issued": {"hi": "जारी", "en": "Issued"},
    "download": {"hi": "डाउनलोड", "en": "Download"},
    "no_certificates": {"hi": "सक्रिय सदस्यता के बाद प्रमाणपत्र यहां दिखेगा.", "en": "Certificates will appear here after an active membership."},
    "create_account": {"hi": "अपना अकाउंट बनाएं", "en": "Create your account"},
    "continue_google": {"hi": "Google से जारी रखें", "en": "Continue with Google"},
    "or": {"hi": "या", "en": "or"},
    "already_registered": {"hi": "पहले से रजिस्टर हैं?", "en": "Already registered?"},
    "member_login": {"hi": "सदस्य लॉगिन", "en": "Member Login"},
    "login_account": {"hi": "अपने अकाउंट में लॉगिन करें", "en": "Log in to your account"},
    "new_member": {"hi": "नए सदस्य हैं?", "en": "New member?"},
    "choose_plan": {"hi": "अपनी सदस्यता चुनें", "en": "Choose your membership"},
    "plans_desc": {
        "hi": "अपनी सेवा यात्रा के लिए उपयुक्त सदस्यता प्लान चुनें.",
        "en": "Choose the right membership plan for your service journey.",
    },
    "free": {"hi": "निशुल्क", "en": "Free"},
    "days_validity": {"hi": "दिन की वैधता", "en": "days validity"},
    "join_now": {"hi": "अभी जुड़ें", "en": "Join now"},
    "login_to_join": {"hi": "लॉगिन करके लें", "en": "Log in to join"},
    "no_plans": {"hi": "अभी कोई सदस्यता प्लान उपलब्ध नहीं है.", "en": "No membership plans are available yet."},
    "secure_payment": {"hi": "सुरक्षित भुगतान", "en": "Secure Payment"},
    "pay_razorpay": {"hi": "Razorpay से भुगतान करें", "en": "Pay with Razorpay"},
    "cancel": {"hi": "रद्द करें", "en": "Cancel"},
    "certificate": {"hi": "प्रमाणपत्र", "en": "Certificate"},
    "back_profile": {"hi": "प्रोफाइल पर वापस", "en": "Back to profile"},
    "reload": {"hi": "रीलोड", "en": "Reload"},
    "fit": {"hi": "फिट", "en": "Fit"},
    "save": {"hi": "सेव", "en": "Save"},
    "clip": {"hi": "क्लिप", "en": "Clip"},
    "print": {"hi": "प्रिंट", "en": "Print"},
    "full": {"hi": "फुल", "en": "Full"},
    "link": {"hi": "लिंक", "en": "Link"},
    "pages": {"hi": "पेज", "en": "Pages"},
    "page": {"hi": "पेज", "en": "Page"},
    "total": {"hi": "कुल", "en": "of"},
    "crop": {"hi": "क्रॉप", "en": "Crop"},
    "all_pages": {"hi": "सभी पेज", "en": "All Pages"},
    "epaper_menu": {"hi": "ई-पेपर मेनू", "en": "E-Paper Menu"},
    "patrika_epaper": {"hi": "पत्रिका ई-पेपर", "en": "Patrika E-Paper"},
    "issue": {"hi": "अंक", "en": "Issue"},
    "date": {"hi": "दिनांक", "en": "Date"},
    "bookmarks": {"hi": "बुकमार्क", "en": "Bookmarks"},
    "no_bookmarks": {"hi": "अभी कोई बुकमार्क पेज नहीं है.", "en": "No bookmarked pages yet."},
    "cropped_page": {"hi": "क्रॉप पेज", "en": "Cropped Page"},
    "share": {"hi": "शेयर", "en": "Share"},
    "crop_again": {"hi": "फिर क्रॉप करें", "en": "Crop Again"},
    "page_images_pending": {"hi": "पेज इमेज अभी तैयार नहीं हैं.", "en": "Page images are not generated yet."},
    "reader_error": {"hi": "इमेज रीडर पेज तैयार नहीं कर पाया:", "en": "Image reader could not generate pages:"},
    "reader_admin_hint": {
        "hi": "इस पत्रिका को admin में खोलकर एक बार सेव करें, या Regenerate page images action चलाएं.",
        "en": "Open this patrika in admin and save it once, or use the Regenerate page images action.",
    },
}


def get_current_language(request):
    language = request.GET.get("lang") or request.session.get(LANGUAGE_SESSION_KEY) or request.COOKIES.get(LANGUAGE_COOKIE_NAME)
    return language if language in SUPPORTED_LANGUAGES else "hi"


def language_context(request):
    current_language = get_current_language(request)
    return {
        "current_lang": current_language,
        "language_options": SUPPORTED_LANGUAGES,
        "ui": {
            key: translations[current_language]
            for key, translations in UI_TEXT.items()
        },
    }
