UI_TEXT = {
    'site_name': 'धर्म रक्षा संघ',
    'nav_toggle': 'मेनू खोलें',
    'home': 'होम',
    'about': 'परिचय',
    'contact': 'संपर्क',
    'events': 'कार्यक्रम',
    'seva_prakalp': 'प्रकल्प',
    'hamare_stambh': 'स्तंभ',
    'patrika': 'पत्रिका',
    'membership': 'सदस्यता',
    'donate': 'दान करें',
    'login': 'लॉगिन',
    'logout': 'लॉगआउट',
    'join': 'जुड़ें',
    'language': 'भाषा',
    'footer_about': 'संगठित सेवा प्रकल्प, सांस्कृतिक मूल्यों और समाज सेवा के माध्यम से राष्ट्रधर्म की सेवा.',
    'hero_eyebrow': 'सेवा. संस्कार. समर्पण.',
    'welcome': 'धर्म रक्षा संघ की आधिकारिक वेबसाइट पर आपका स्वागत है.',
    'view': 'देखें',
    'all_seva': 'सभी सेवा प्रकल्प',
    'active_prakalp': 'सक्रिय सेवा प्रकल्प',
    'core_values': 'मूल मूल्य',
    'seva': 'सेवा',
    'sanskar': 'संस्कार',
    'sangathan': 'संगठन',
    'seva_desc': 'समर्पण के साथ समाज सेवा',
    'sanskar_desc': 'हर पीढ़ी के लिए सांस्कृतिक मूल्य',
    'sangathan_desc': 'स्थायी प्रभाव के लिए संगठित प्रयास',
    'stambh_heading': 'मिशन को दिशा देने वाले व्यक्तित्व',
    'view_all': 'सभी देखें',
    'read_details': 'विवरण पढ़ें',
    'publications': 'प्रकाशन',
    'featured_issue': 'विशेष अंक',
    'pdf_download': 'PDF डाउनलोड',
    'read_epaper': 'पत्रिका पढ़ें',
    'cta_title': 'धर्म रक्षा संघ',
    'cta_text': 'हर प्रकल्प सेवा भाव रखने वाले लोगों से शुरू होता है.',
    'explore_seva': 'सेवा प्रकल्प देखें',
    'contact_us': 'संपर्क करें',
    'email': 'ईमेल',
    'mobile': 'मोबाइल',
    'bank_details': 'बैंक विवरण',
    'account_info': 'खाता जानकारी',
    'scan_donate': 'स्कैन करें और दान दें',
    'our_work': 'हमारा कार्य',
    'seva_index_desc': 'धर्म रक्षा संघ के सक्रिय सेवा कार्यों और प्रकल्पों को देखें.',
    'no_prakalp': 'अभी कोई सेवा प्रकल्प उपलब्ध नहीं है.',
    'our_pillars': 'हमारे स्तंभ',
    'stambh_desc': 'धर्म रक्षा संघ की प्रेरणा, मार्गदर्शन और संगठन शक्ति.',
    'featured': 'विशेष',
    'no_stambh': 'अभी कोई स्तंभ उपलब्ध नहीं है.',
    'events_desc': 'धर्म रक्षा संघ के स्थायी, वर्तमान, विशेष और पूर्व कार्यक्रम.',
    'featured_events': 'विशेष कार्यक्रम',
    'any_time': 'स्थायी',
    'any_time_events': 'स्थायी कार्यक्रम',
    'current_events': 'वर्तमान कार्यक्रम',
    'past_events': 'पूर्व कार्यक्रम',
    'no_events': 'अभी कोई कार्यक्रम उपलब्ध नहीं है.',
    'back_events': 'कार्यक्रमों पर वापस',
    'back_seva': 'सेवा प्रकल्प पर वापस',
    'back_stambh': 'हमारे स्तंभ पर वापस',
    'patrika_desc': 'धर्म रक्षा संघ की अपलोड की गई पत्रिकाएं पढ़ें और डाउनलोड करें.',
    'no_patrika': 'अभी कोई पत्रिका उपलब्ध नहीं है.',
    'my_profile': 'मेरी प्रोफाइल',
    'member_profile': 'सदस्य प्रोफाइल',
    'update_details': 'विवरण अपडेट करें',
    'save_details': 'विवरण सेव करें',
    'subscriptions': 'सदस्यता',
    'valid_until': 'तक मान्य',
    'no_membership': 'अभी कोई सक्रिय सदस्यता नहीं है.',
    'choose_membership': 'सदस्यता लें',
    'certificates': 'प्रमाणपत्र',
    'issued': 'जारी',
    'download': 'डाउनलोड',
    'no_certificates': 'सक्रिय सदस्यता के बाद प्रमाणपत्र यहां दिखेगा.',
    'create_account': 'अपना अकाउंट बनाएं',
    'continue_google': 'Google से जारी रखें',
    'or': 'या',
    'already_registered': 'पहले से रजिस्टर हैं?',
    'member_login': 'सदस्य लॉगिन',
    'login_account': 'अपने अकाउंट में लॉगिन करें',
    'new_member': 'नए सदस्य हैं?',
    'choose_plan': 'अपनी सदस्यता चुनें',
    'plans_desc': 'हमसे जुड़ने के लिए उपयुक्त सदस्यता प्लान चुनें.',
    'free': 'निशुल्क',
    'days_validity': 'दिन की वैधता',
    'lifetime_free': 'आजीवन निशुल्क',
    'membership_banner_alt': 'धर्म रक्षा संघ सदस्यता अभियान',
    'join_now': 'अभी जुड़ें',
    'login_to_join': 'लॉगिन करके लें',
    'no_plans': 'अभी कोई सदस्यता प्लान उपलब्ध नहीं है.',
    'secure_payment': 'सुरक्षित भुगतान',
    'pay_razorpay': 'Razorpay से भुगतान करें',
    'cancel': 'रद्द करें',
    'certificate': 'प्रमाणपत्र',
    'back_profile': 'प्रोफाइल पर वापस',
    'reload': 'रीलोड',
    'fit': 'फिट',
    'save': 'सेव',
    'clip': 'क्लिप',
    'print': 'प्रिंट',
    'full': 'फुल',
    'link': 'लिंक',
    'pages': 'पेज',
    'page': 'पेज',
    'total': 'कुल',
    'crop': 'क्रॉप',
    'all_pages': 'सभी पेज',
    'epaper_menu': 'ई-पेपर मेनू',
    'patrika_epaper': 'पत्रिका ई-पेपर',
    'issue': 'अंक',
    'date': 'दिनांक',
    'bookmarks': 'बुकमार्क',
    'no_bookmarks': 'अभी कोई बुकमार्क पेज नहीं है.',
    'cropped_page': 'क्रॉप पेज',
    'share': 'शेयर',
    'crop_again': 'फिर क्रॉप करें',
    'page_images_pending': 'पेज इमेज अभी तैयार नहीं हैं.',
    'reader_error': 'इमेज रीडर पेज तैयार नहीं कर पाया:',
    'reader_admin_hint': 'इस पत्रिका को admin में खोलकर एक बार सेव करें, या Regenerate page images action चलाएं.',
}


def language_context(request):
    return {
        "ui": UI_TEXT,
    }
